stages:
  - deploy
deploy_staging:
  stage: deploy
  script:
  - rm -rf ~/go/src/github.com/mattermost/mattermost-server/*
  - cd && scp -r builds/a8b78ce1/0/nal/mmc-server/* go/src/github.com/mattermost/mattermost-server/
  #- cd go/src/github.com/mattermost/mattermost-webapp && make build
  #- cd ~/go/src/github.com/mattermost/mattermost-server/ && make build && make package
  only:
    - cicd
  tags:
    - shell-runner-3

