stages:
  - build-server
build_server:
  stage: build-server
  script:
   - sudo rm -rf ~/go/src/github.com/mattermost/mattermost-server
   - mkdir -p ~/go/src/github.com/mattermost/mattermost-server
   - cp -r * ~/go/src/github.com/mattermost/mattermost-server/
   - cp -f /opt/mattermost-ci/config.json ~/go/src/github.com/mattermost/mattermost-server/config/config.json
   - cd ~/go/src/github.com/mattermost/mattermost-server/
   - make build
   - make package
   - sudo cp dist/mattermost-team-linux-amd64.tar.gz /opt/
   - cd /opt
   - sudo tar -zxvf mattermost-team-linux-amd64.tar.gz
   - sudo id -u mattermost &>/dev/null || sudo useradd --system --user-group mattermost 
   - sudo chown -R mattermost:mattermost /opt/mattermost
   - sudo chmod -R g+w /opt/mattermost
  only:
    - develop
  tags:
    - mmc-demo-runner